platform :ios, "7.0"

pod 'AFNetworking', "~> 1.0"
pod 'VCRURLConnection', :git => 'https://github.com/dstnbrkr/VCRURLConnection.git', :commit => '75f7ba74'
pod 'DRBOperationTree', :git => 'https://github.com/dstnbrkr/DRBOperationTree.git'




